### ISSUE TITLE
test fails

### ISSUE THREAD

**Issue by alexbodn** [fulfilio/nereid-webshop#56]
hello friends,

i'd like to try tryton, by the nereid approach.
my first aim would be to build a shop by scripts, following the test scripts.
unfortunately, 30 of the tests are failing, so i don't know how to proceed.

i'll be willing to work on the problem and then offer a pull. since it's all about a multi layered piece of software, i'd dare ask for a little initiation from your part.
would anybody give me a hint?

alex

**Comment by alexbodn** [comment]
the typo fixed.  pull requested.
i hope i'll find the more important bug.

**Comment by prakashpp** [comment]
#59 fixes all the tests.

**Comment by alexbodn** [comment]
thank you very much. 
it was important for me, 
to allow me bootstrap a server 
in the same manner as the test goes.

alex
